import { Athlete, Alert, TeamOverview } from "./types";

export const MOCK_ATHLETES: Athlete[] = [
  {
    id: "a1",
    name: "Marcus Johnson",
    position: "Forward",
    recoveryScore: 82,
    injuryStatus: "Healthy",
    lastUpdated: "2 hours ago",
    streakDays: 5,
    points: 1250,
    biometrics: {
      sleep: 85,
      hydration: 90,
      soreness: 70,
      fatigue: 80,
      stress: 85,
      trainingLoad: 60,
    },
    pastInjuries: [
      {
        id: "i1",
        type: "Ankle Sprain",
        date: "2023-11-10",
        resolvedDate: "2023-12-05",
        status: "resolved",
      },
    ],
  },
  {
    id: "a2",
    name: "David Chen",
    position: "Midfielder",
    recoveryScore: 45,
    injuryStatus: "Injured",
    lastUpdated: "1 hour ago",
    streakDays: 0,
    points: 840,
    biometrics: {
      sleep: 50,
      hydration: 60,
      soreness: 30,
      fatigue: 40,
      stress: 55,
      trainingLoad: 0,
    },
    currentInjury: {
      type: "Hamstring Strain",
      severity: "medium",
      timeline: "3-4 weeks",
      rehabPlan: "Light stretching, ice therapy, rest",
    },
    pastInjuries: [
      {
        id: "i2",
        type: "Hamstring Strain",
        date: "2024-05-15",
        status: "current",
      },
    ],
  },
  {
    id: "a3",
    name: "James Wilson",
    position: "Defender",
    recoveryScore: 68,
    injuryStatus: "Caution",
    lastUpdated: "3 hours ago",
    streakDays: 2,
    points: 1050,
    biometrics: {
      sleep: 65,
      hydration: 70,
      soreness: 60,
      fatigue: 65,
      stress: 75,
      trainingLoad: 80,
    },
    pastInjuries: [],
  },
  {
    id: "a4",
    name: "Michael Smith",
    position: "Goalkeeper",
    recoveryScore: 95,
    injuryStatus: "Healthy",
    lastUpdated: "5 hours ago",
    streakDays: 12,
    points: 2100,
    biometrics: {
      sleep: 95,
      hydration: 100,
      soreness: 90,
      fatigue: 95,
      stress: 90,
      trainingLoad: 40,
    },
    pastInjuries: [],
  },
  {
    id: "a5",
    name: "Robert Davis",
    position: "Forward",
    recoveryScore: 55,
    injuryStatus: "Caution",
    lastUpdated: "4 hours ago",
    streakDays: 1,
    points: 920,
    biometrics: {
      sleep: 55,
      hydration: 80,
      soreness: 45,
      fatigue: 50,
      stress: 60,
      trainingLoad: 85,
    },
    pastInjuries: [],
  },
  {
    id: "a6",
    name: "William Brown",
    position: "Midfielder",
    recoveryScore: 78,
    injuryStatus: "Healthy",
    lastUpdated: "2 hours ago",
    streakDays: 4,
    points: 1100,
    biometrics: {
      sleep: 80,
      hydration: 85,
      soreness: 75,
      fatigue: 70,
      stress: 80,
      trainingLoad: 70,
    },
    pastInjuries: [],
  },
  {
    id: "a7",
    name: "Richard Taylor",
    position: "Defender",
    recoveryScore: 88,
    injuryStatus: "Healthy",
    lastUpdated: "1 hour ago",
    streakDays: 7,
    points: 1500,
    biometrics: {
      sleep: 90,
      hydration: 85,
      soreness: 80,
      fatigue: 85,
      stress: 90,
      trainingLoad: 60,
    },
    pastInjuries: [],
  },
  {
    id: "a8",
    name: "Joseph Anderson",
    position: "Defender",
    recoveryScore: 35,
    injuryStatus: "Injured",
    lastUpdated: "10 mins ago",
    streakDays: 0,
    points: 600,
    biometrics: {
      sleep: 40,
      hydration: 50,
      soreness: 20,
      fatigue: 30,
      stress: 40,
      trainingLoad: 0,
    },
    currentInjury: {
      type: "ACL Tear",
      severity: "high",
      timeline: "6-9 months",
      rehabPlan: "Surgery scheduled, post-op physio",
    },
    pastInjuries: [
      {
        id: "i3",
        type: "ACL Tear",
        date: "2024-04-20",
        status: "current",
      },
    ],
  },
  {
    id: "a9",
    name: "Thomas Thomas",
    position: "Midfielder",
    recoveryScore: 72,
    injuryStatus: "Healthy",
    lastUpdated: "6 hours ago",
    streakDays: 3,
    points: 980,
    biometrics: {
      sleep: 70,
      hydration: 75,
      soreness: 65,
      fatigue: 75,
      stress: 70,
      trainingLoad: 65,
    },
    pastInjuries: [],
  },
  {
    id: "a10",
    name: "Charles Jackson",
    position: "Forward",
    recoveryScore: 62,
    injuryStatus: "Caution",
    lastUpdated: "30 mins ago",
    streakDays: 2,
    points: 890,
    biometrics: {
      sleep: 60,
      hydration: 65,
      soreness: 55,
      fatigue: 60,
      stress: 65,
      trainingLoad: 75,
    },
    pastInjuries: [],
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "al1",
    athleteId: "a8",
    athleteName: "Joseph Anderson",
    type: "injury",
    severity: "high",
    message: "Severe knee pain reported during training.",
    date: "2024-05-20",
    isResolved: false,
  },
  {
    id: "al2",
    athleteId: "a5",
    athleteName: "Robert Davis",
    type: "workload",
    severity: "medium",
    message: "Training load exceeds recommended threshold by 20%.",
    date: "2024-05-21",
    isResolved: false,
  },
  {
    id: "al3",
    athleteId: "a2",
    athleteName: "David Chen",
    type: "recovery",
    severity: "medium",
    message: "Poor sleep quality reported (4 hours) for 2 consecutive days.",
    date: "2024-05-21",
    isResolved: false,
  },
  {
    id: "al4",
    athleteId: "a1",
    athleteName: "Marcus Johnson",
    type: "recovery",
    severity: "low",
    message: "Hydration levels returning to normal.",
    date: "2024-05-19",
    isResolved: true,
  },
];

export const MOCK_TEAM_OVERVIEW: TeamOverview = {
  avgRecoveryScore: 68,
  highRiskCount: 2,
  totalAthletes: 10,
  workloadAlertsCount: 3,
  injuryRiskAlertsCount: 2,
};
