import { NextResponse } from "next/server";

async function runGeminiChat(message: string, apiKey: string) {
  if (!apiKey) {
    throw new Error("Gemini API key is not configured.");
  }

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [
              {
                text: message,
              },
            ],
          },
        ],
        systemInstruction: {
          parts: [
            {
              text: "You are a helpful and supportive AI assistant.",
            },
          ],
        },
      }),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Gemini API returned status ${response.status}: ${errorText}`);
  }

  const data = await response.json();
  const reply = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!reply) {
    throw new Error("No response content generated by Gemini.");
  }
  return reply;
}

async function runOpenRouterChat(message: string, apiKey: string, modelName: string) {
  if (!apiKey) {
    throw new Error("OpenRouter API key is not configured.");
  }

  const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: modelName,
      messages: [
        { role: "system", content: "You are a helpful and supportive AI assistant." },
        { role: "user", content: message },
      ],
      temperature: 0.6,
      max_tokens: 500,
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenRouter returned status ${response.status}: ${await response.text()}`);
  }

  const data = await response.json();
  const reply = data.choices?.[0]?.message?.content;
  if (!reply) {
    throw new Error("No response content generated by OpenRouter.");
  }
  return reply;
}

export async function POST(req: Request) {
  try {
    const { message } = await req.json();
    
    // 1. Try Gemini first if GEMINI_API_KEY is available
    const geminiApiKey = process.env.GEMINI_API_KEY || "";
    if (geminiApiKey) {
      try {
        const reply = await runGeminiChat(message, geminiApiKey);
        return NextResponse.json({ reply });
      } catch (geminiError: any) {
        console.warn("Gemini API failed, falling back to OpenRouter:", geminiError.message);
      }
    }

    // 2. Fallback to OpenRouter
    const openRouterApiKey = process.env.OPENROUTER_API_KEY || "";
    if (openRouterApiKey) {
      const preferredModel = process.env.OPENROUTER_MODEL || "openai/gpt-oss-120b";
      try {
        const reply = await runOpenRouterChat(message, openRouterApiKey, preferredModel);
        return NextResponse.json({ reply });
      } catch (orError: any) {
        console.warn(`OpenRouter preferred model (${preferredModel}) failed, trying free fallback:`, orError.message);
        const reply = await runOpenRouterChat(message, openRouterApiKey, "openai/gpt-oss-20b:free");
        return NextResponse.json({ reply });
      }
    }

    throw new Error("No working API key or model configuration was found.");
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "An unexpected error occurred" },
      { status: 500 }
    );
  }
}

